# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :build_and_test do
    # Build the project
    gym

    # Run tests
    scan
  end

  lane :deploy_to_app_store do
    # Increment the build number
    increment_build_number

    # Build and release to App Store
    gym
    deliver
  end
end

lane :build_simulator do
  build_app(
    scheme: "QuatesApp",
    sdk: "iphonesimulator",
    clean: true,
    export_method: "development",  # симулятор не требует подписи
    skip_codesigning: true          # отключаем подпись
  )

  run_tests(
    scheme: "QuatesApp",
    device: "iPhone 14"
  )
end