# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :build_and_test do    
    # Increment the build number
    increment_build_number
  end

  lane :build_simulator do
  build_app(
    scheme: "QuatesApp",
    sdk: "iphonesimulator",
    clean: true,
    configuration: "Debug",
    export_method: "development",  # симулятор не требует подписи
    skip_codesigning: true          # отключаем подпись
  )
  end
end