name: CI for iOS

on:
  push:
    branches:
      - some-tests

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1️⃣ Получаем код
      - name: Checkout repository
        uses: actions/checkout@v5

      # 2️⃣ Показываем доступные Xcode
      - name: Show available Xcode versions
        run: |
          echo "Installed Xcode versions:"
          ls /Applications/ | grep Xcode
          echo "Active Xcode version:"
          xcodebuild -version

      # 3️⃣ Выбираем версию Xcode
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26.0.0'

      # 4️⃣ Устанавливаем линтер и форматтер
      - name: Install SwiftLint & SwiftFormat
        run: |
          brew install swiftlint
          brew install swiftformat

      # 5️⃣ Запускаем линтер в строгом режиме
      - name: Run SwiftLint
        run: |
          swiftlint lint --config .swiftlint.yml

      # 6️⃣ Запускаем форматтер в режиме проверки
      - name: Check SwiftFormat
        run: |
          swiftformat . --lint --config .swiftformat

      # 7️⃣ Сборка проекта
      - name: Build project
        run: |
          xcodebuild \
            -scheme QuatesApp \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 17,OS=latest' \
            clean build
